[theme]

primaryColor = 'rgba(246, 245, 244)'
#secondaryBackgroundColor = 'rgba(218, 217, 216)'

font = "'PT Sans Narrow':https://fonts.googleapis.com/css2?family=PT+Sans+Narrow:wght@400;700&display=swap"
headingFont = "'PT Sans Narrow':https://fonts.googleapis.com/css2?family=PT+Sans+Narrow:wght@400;700&display=swap"

baseFontSize = 16

headingFontSizes = ["3rem", "2rem", "1rem"]
headingFontWeights = [700, 600, 600]

showWidgetBorder = true
borderColor = "#64625F"
