[project]
name = "trust_streamlit_demo"
version = "0.1.0"
description = "Streamlit demo of coaching tool for advisors."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "streamlit>=1.52",
    "polars>=1.37",
    "pandas>=2.3.0",
    "numpy>=2.4.0",
    "matplotlib>=3.10.0",
    "kaleido>=1.2.0",
    "openpyxl>=3.1.0"
    "plotly>=6.5.0",
    "scipy>=1.17.0",
]